apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: dis-system-store
  namespace: flux-system
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      environmentType: PublicCloud
      serviceAccountRef:
        name: dis-secret-sync-sa
      vaultUrl: "${DIS_SYSTEM_KV_URL}"
