apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dis-vault-operator
  namespace: flux-system
spec:
  force: false
  interval: 5m0s
  path: ./default
  postBuild:
    substitute:
      DISVAULT_AZURE_SUBSCRIPTION_ID: ${DISVAULT_AZURE_SUBSCRIPTION_ID}
      DISVAULT_RESOURCE_GROUP: ${DISVAULT_RESOURCE_GROUP}
      DISVAULT_AZURE_TENANT_ID: ${DISVAULT_AZURE_TENANT_ID}
      DISVAULT_LOCATION: ${DISVAULT_LOCATION}
      DISVAULT_ENV: ${DISVAULT_ENV}
      DISVAULT_AKS_SUBNET_IDS: ${DISVAULT_AKS_SUBNET_IDS}
      DISVAULT_VPN_EXIT_NODE_SUBNET_ID: ${DISVAULT_VPN_EXIT_NODE_SUBNET_ID}
  prune: false
  retryInterval: 5m0s
  images:
    - name: controller
      newName: altinncr.azurecr.io/ghcr.io/altinn/altinn-platform/dis-vault-operator
      # renovate: datasource=docker depName=ghcr.io/altinn/altinn-platform/dis-vault-operator versioning=semver
      newTag: v1.4.2
  sourceRef:
    kind: OCIRepository
    name: dis-vault-operator
    namespace: flux-system
  targetNamespace: dis-vault-operator-system
  timeout: 5m0s
  wait: true
