apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: ${REDIRECT_NAME}-tls
  namespace: ${REDIRECT_TLS_SECRET_NAMESPACE}
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: ${REDIRECT_NAMESPACE:=traefik}
  to:
    - group: ""
      kind: Secret
      name: ${REDIRECT_TLS_SECRET_NAME}
