apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - target:
      kind: HelmRelease
      name: linkerd
    patch: |
      - op: add
        path: /spec/values/podMonitor/labels
        value:
          release: kube-prometheus-stack
      - op: remove
        path: /spec/postRenderers
