apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - envoy-proxy.yaml
  - tls-secrets.yaml
  - gateway-api-resources.yaml
  - http-redirect.yaml
  - backend-traffic-policy.yaml
  - client-traffic-policy.yaml
