apiVersion: v1
kind: ServiceAccount
metadata:
  name: dis-tls-cert-kv-uami
  namespace: envoy-gateway-system
  annotations:
    azure.workload.identity/client-id: "${DIS_TLS_READER_CLIENT_ID}"
    azure.workload.identity/tenant-id: "${DIS_TLS_READER_TENANT_ID}"
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: dis-tls-cert-store
  namespace: envoy-gateway-system
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      environmentType: PublicCloud
      serviceAccountRef:
        name: dis-tls-cert-kv-uami
        namespace: envoy-gateway-system
      vaultUrl: "${DIS_TLS_KV_URI}"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tls-cert
  namespace: envoy-gateway-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: dis-tls-cert-store
  target:
    name: tls-cert
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: '{{ .crt }}'
        tls.key: '{{ .key }}'
  data:
    - secretKey: crt
      remoteRef:
        key: "${DIS_TLS_CRT_SECRET_NAME}"
    - secretKey: key
      remoteRef:
        key: "${DIS_TLS_KEY_SECRET_NAME}"
