apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: derper-tls
  namespace: derper
spec:
  secretName: derper-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - "${DERP_HOSTNAME}"
