apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: whoami
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - image: altinncr.azurecr.io/docker.io/traefik/whoami
          imagePullPolicy: IfNotPresent
          name: whoami
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
          securityContext:
            readOnlyRootFilesystem: true
          livenessProbe:
            httpGet:
              path: /health
              port: 80
          readinessProbe:
            httpGet:
              path: /health
              port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: whoami
spec:
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv6
    - IPv4
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    app: whoami
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: l5d-header-middleware
  namespace: whoami
spec:
  headers:
    customRequestHeaders:
      l5d-dst-override: whoami.whoami.svc.cluster.local:80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
  namespace: whoami
spec:
  entryPoints:
    - http
    - https
  routes:
    - kind: Rule
      match: HostRegexp(`^.*\.?altinn\.(no|cloud)$`) && (PathPrefix(`/whoami/`) || Path(`/whoami`))
      middlewares:
        - name: l5d-header-middleware
          namespace: whoami
      services:
        - name: whoami
          namespace: whoami
          port: 80
