apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: platform-admins
  namespace: platform-system
subjects:
  - kind: Group
    name: "09599a84-645b-4217-853f-01700a17cd4a"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
