apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: headplane
  namespace: headplane
spec:
  gatewayClassName: traefik
  listeners:
    - name: https
      port: 8443
      protocol: HTTPS
      hostname: headplane.altinn.cloud
      tls:
        certificateRefs:
          - name: headplane-tls
      allowedRoutes:
        namespaces:
          from: Same
