apiVersion: v1
kind: Secret
metadata:
  name: headplane-config
  namespace: headplane
type: Opaque
stringData:
  config.yaml: |
    server:
      host: "::"
      port: 3000
      base_url: "https://headplane.altinn.cloud"
      cookie_secret: "${HEADPLANE_COOKIE_SECRET}"
      cookie_secure: true
      data_path: "/var/lib/headplane"

    headscale:
      url: "http://headscale.headscale.svc.cluster.local.:8080"
      api_key: "${HEADPLANE_API_KEY}"

    oidc:
      issuer: "https://login.microsoftonline.com/cd0026d8-283b-4a55-9bfa-d0ef4a8ba21c/v2.0"
      client_id: "${HEADPLANE_APP_CLIENT_ID}"
      client_secret: "${HEADPLANE_APP_CLIENT_SECRET}"
      headscale_api_key: "${HEADPLANE_API_KEY}"
      use_pkce: true
      disable_api_key_login: true
      profile_picture_source: "gravatar"
