apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: headscale
  namespace: headscale
spec:
  parentRefs:
    - name: headscale
      sectionName: websecure
  hostnames:
    - headscale.altinn.cloud
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: headscale
          port: 8080
