apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: headscale-data
  namespace: headscale
spec:
  storageClassName: headscale-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
