apiVersion: v1
kind: ServiceAccount
metadata:
  name: dis-tls-cert-kv-uami
  namespace: traefik
  annotations:
    azure.workload.identity/client-id: ${CERT_KV_UAMI_CLIENT_ID}
    azure.workload.identity/tenant-id: ${CERT_KV_TENANT_ID:=cd0026d8-283b-4a55-9bfa-d0ef4a8ba21c}
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: dis-tls-cert-store
  namespace: traefik
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://dis-tls-cert.vault.azure.net"
      serviceAccountRef:
        name: dis-tls-cert-kv-uami
        namespace: traefik
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ssl-cert
  namespace: traefik
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: dis-tls-cert-store
  target:
    name: ssl-cert
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: '{{ .crt }}'
        tls.key: '{{ .key }}'
  data:
    - secretKey: crt
      remoteRef:
        key: ${KV_SECRET_NAME_CERT}
    - secretKey: key
      remoteRef:
        key: ${KV_SECRET_NAME_KEY}
