---
apiVersion: policy.linkerd.io/v1beta3
kind: Server
metadata:
  name: otel-collector-grpc
  namespace: monitoring
spec:
  accessPolicy: cluster-unauthenticated
  podSelector:
    matchLabels:
      app.kubernetes.io/name: otel-collector
  port: 4317
  proxyProtocol: unknown
---
apiVersion: policy.linkerd.io/v1beta3
kind: Server
metadata:
  name: otel-collector-http
  namespace: monitoring
spec:
  accessPolicy: cluster-unauthenticated
  podSelector:
    matchLabels:
      app.kubernetes.io/name: otel-collector
  port: 4318
  proxyProtocol: unknown
