apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: azure-managed-prometheus
  namespace: grafana-public
spec:
  instanceSelector:
    matchLabels:
      dashboards: "public-grafana"
  uid: azure-managed-prometheus
  datasource:
    name: Azure Managed Prometheus
    type: grafana-azureprometheus-datasource
    access: proxy
    url: "${GRAFANA_PUBLIC_PROMETHEUS_URL}"
    jsonData:
      httpMethod: POST
      azureCredentials:
        authType: workloadidentity
      timeoutSeconds: 30
