apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: allow-flux-system
  namespace: kyverno
spec:
  exceptions:
  - policyName: disallow-host-path
    ruleNames:
    - host-path
    - autogen-host-path
  match:
    any:
    - resources:
        kinds:
        - Pod
        - Deployment
        - ReplicaSet
        namespaces:
        - flux-system
