apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ssl-cert
  namespace: traefik
spec:
  secretName: ssl-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - "${CERT_DNS_NAME}"
