apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  chart:
    spec:
      chart: kyverno
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: kyverno
      # renovate: datasource=helm registryUrl=https://kyverno.github.io/kyverno/ packageName=kyverno
      version: 3.7.0
  interval: 1h
  timeout: 5m
  install:
    crds: CreateReplace
    remediation:
      retries: 5
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 5
  values:
    global:
      image:
        registry: altinncr.azurecr.io/ghcr.io
    reportsController:
      metering:
        config: grpc
        port: ${OTEL_PORT:=4317}
        collector: "${OTEL_URL:=otel-collector.monitoring.svc.cluster.local}"
    cleanupController:
      metering:
        config: grpc
        port: ${OTEL_PORT:=4317}
        collector: "${OTEL_URL:=otel-collector.monitoring.svc.cluster.local}"
    backgroundController:
      metering:
        config: grpc
        port: ${OTEL_PORT:=4317}
        collector: "${OTEL_URL:=otel-collector.monitoring.svc.cluster.local}"
    admissionController:
      metering:
        config: grpc
        port: ${OTEL_PORT:=4317}
        collector: "${OTEL_URL:=otel-collector.monitoring.svc.cluster.local}"