apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - target:
      kind: GitRepository
      name: gateway-api
    patch: |
      - op: replace
        path: /metadata/namespace
        value: platform-system
  - target:
      kind: Kustomization
      name: gateway-api-crds
    patch: |
      - op: replace
        path: /metadata/namespace
        value: platform-system
      - op: replace
        path: /spec/sourceRef/namespace
        value: platform-system
