apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${REDIRECT_TLS_SECRET_NAME:=${REDIRECT_NAME}-tls}
  namespace: ${REDIRECT_TLS_SECRET_NAMESPACE:=${REDIRECT_NAMESPACE:=traefik}}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ${REDIRECT_SECRET_STORE_KIND:=SecretStore}
    name: ${REDIRECT_SECRET_STORE_NAME}
  target:
    name: ${REDIRECT_TLS_SECRET_NAME:=${REDIRECT_NAME}-tls}
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: '{{ .crt }}'
        tls.key: '{{ .key }}'
  data:
    - secretKey: crt
      remoteRef:
        key: ${REDIRECT_REMOTE_SECRET_NAME_CERT}
    - secretKey: key
      remoteRef:
        key: ${REDIRECT_REMOTE_SECRET_NAME_KEY}
