apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: altinn-keyvault-store
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      environmentType: PublicCloud
      serviceAccountRef:
        name: altinn-kv-eso
        namespace: external-secrets
      vaultUrl: "${ALTINN_KV_URL}"
