apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: dis-identity-operator
  namespace: flux-system
spec:
  interval: 5m0s
  provider: azure
  ref:
    # renovate: datasource=docker depName=ghcr.io/altinn/altinn-platform/dis-identity-operator versioning=semver
    tag: v0.1.1
  timeout: 5m0s
  url: oci://altinncr.azurecr.io/dis/kustomize/dis-identity-operator
