apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno-policies
  namespace: kyverno-policies
spec:
  chart:
    spec:
      chart: kyverno-policies
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: kyverno
      # renovate: datasource=helm registryUrl=https://kyverno.github.io/kyverno/ packageName=kyverno-policies
      version: 3.6.3
  interval: 1h
  timeout: 5m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  # values:
