apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: activemq-eformidling-data
  namespace: activemq
spec:
  storageClassName: activemq-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
