apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dis-cache-operator
  namespace: flux-system
spec:
  force: false
  interval: 5m0s
  path: ./default
  postBuild:
    substitute:
      DISCACHE_VALKEY_IMAGE: ${DISCACHE_VALKEY_IMAGE}
      DISCACHE_EXPORTER_IMAGE: ${DISCACHE_EXPORTER_IMAGE}
  prune: false
  retryInterval: 5m0s
  images:
    - name: controller
      newName: altinncr.azurecr.io/ghcr.io/altinn/altinn-platform/dis-cache-operator
      # renovate: datasource=docker depName=ghcr.io/altinn/altinn-platform/dis-cache-operator versioning=semver
      newTag: v0.1.0
  sourceRef:
    kind: OCIRepository
    name: dis-cache-operator
    namespace: flux-system
  targetNamespace: dis-cache-operator-system
  timeout: 5m0s
  wait: true
