apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keys
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: datakeys
