apiVersion: v1
kind: ServiceAccount
metadata:
  name: altinn-kv-eso
  namespace: external-secrets
  annotations:
    azure.workload.identity/client-id: "${ALTINN_KV_ESO_CLIENT_ID}"
    azure.workload.identity/tenant-id: "${TENANT_ID}"
  labels:
    azure.workload.identity/use: "true"
