apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: serviceowner-keyvault-store
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      environmentType: PublicCloud
      serviceAccountRef:
        name: so-kv-eso
        namespace: external-secrets
      vaultUrl: "${SO_KV_URL}"
