apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: accesstokencredentials-kv-store
  namespace: default
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: ${ALTINN_KV_URI}
      serviceAccountRef:
        name: ${ALTINN_KV_SERVICE_ACCOUNT_NAME}
        namespace: default
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: accesstokencredentials
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: accesstokencredentials-kv-store
  target:
    name: accesstoken
    creationPolicy: Owner
  data:
    - secretKey: accesstokencredentials.pfx
      remoteRef:
        key: accesstokencredentials
