apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: platform-at23-altinn-cloud
  namespace: dis-tls-cert
spec:
  secretName: platform-at23-altinn-cloud
  issuerRef:
    name: zerossl-dis-tls-cert
    kind: ClusterIssuer
  dnsNames:
    - platform.at23.altinn.cloud
