apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: skd-apps-yt01-altinn-cloud
  namespace: dis-tls-cert
spec:
  secretName: skd-apps-yt01-altinn-cloud
  issuerRef:
    name: zerossl-dis-tls-cert
    kind: ClusterIssuer
  dnsNames:
    - skd.apps.yt01.altinn.cloud
