apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: star-altinn-cloud
  namespace: dis-tls-cert
spec:
  secretName: star-altinn-cloud
  issuerRef:
    name: zerossl-dis-tls-cert
    kind: ClusterIssuer
  dnsNames:
    - "*.altinn.cloud"
