apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - hsts-middleware.yaml
  - hsts-middleware-default.yaml
  - root-ingress-route.yaml
patches:
  - target:
      kind: HelmRelease
      name: altinn-traefik
    patch: |
      - op: add
        path: /spec/values/ports/https/http/middlewares
        value:
          - traefik-hsts-header@kubernetescrd
