apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - target:
      kind: HelmRelease
      name: linkerd
    patch: |
      - op: replace
        path: /spec/values/podMonitor/enabled
        value: false
      - op: remove
        path: /spec/postRenderers
