apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: simplewebapp.kro.run
spec:
  schema:
    apiVersion: v1alpha1
    kind: SimpleWebApp
    spec:
      name: string
      namespace: string
      image: string
      replicas: integer | default=1
      port: integer | default=80
    status:
      deploymentReady: ${deployment.status.readyReplicas}
  resources:
    - id: deployment
      template:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: ${schema.spec.name}
          namespace: ${schema.spec.namespace}
        spec:
          replicas: ${schema.spec.replicas}
          selector:
            matchLabels:
              app: ${schema.spec.name}
          template:
            metadata:
              labels:
                app: ${schema.spec.name}
            spec:
              containers:
                - name: main
                  image: ${schema.spec.image}
                  ports:
                    - containerPort: ${schema.spec.port}
    - id: service
      template:
        apiVersion: v1
        kind: Service
        metadata:
          name: ${schema.spec.name}
          namespace: ${schema.spec.namespace}
        spec:
          selector:
            app: ${schema.spec.name}
          ports:
            - port: ${schema.spec.port}
              targetPort: ${schema.spec.port}
