apiVersion: v1
kind: Secret
metadata:
  name: tailscale-authkey
  namespace: tailscale-subnet-router
stringData:
  # Generate with: headscale preauthkeys create --reusable --tags tag:<aks_name>
  TS_AUTHKEY: "HEADSCALE_PREAUTH_KEY"
