apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: lakmus-config
  namespace: flux-system
spec:
  interval: 5m0s
  provider: azure
  ref:
    # renovate: datasource=docker depName=ghcr.io/altinn/altinn-platform/lakmus versioning=semver
    tag: v1.1.0
  timeout: 5m0s
  url: oci://altinncr.azurecr.io/dis/kustomize/lakmus
