name: Pull Request

on:
  pull_request:
    branches: [main]

concurrency:
  group: pull-request-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  kustomize-diff:
    uses: dis-way/actions/.github/workflows/kustomize-diff.yml@de79ff78153ee83ec9743c7e41c9e7cd7ac0f63c # main
    with:
      build-paths: "oci/*,oci/*/apps,oci/*/multitenancy,oci/*/adminservices,oci/*/platform-aks"
    permissions:
      contents: read
      pull-requests: write
