name: Pull Request

on:
  pull_request:
    branches: [main]

concurrency:
  group: pull-request-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  kustomize-diff:
    uses: dis-way/actions/.github/workflows/kustomize-diff.yml@9e1a4cd8ee60417e7097ec7b518c1fe79b263c4a # main
    with:
      build-paths: "oci/*,oci/*/apps,oci/*/multitenancy,oci/*/adminservices,oci/*/platform-aks"
    permissions:
      contents: read
      pull-requests: write
